name: Build

on:
  push:
    branches: [ci-testing]


concurrency:
  group: build-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  test:
    strategy:
      fail-fast: false
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/k4zoku/tosu-overlay-build-ci:1.0.0
    steps:
      - name: Checkout ðŸ›’
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build ðŸ—ï¸
        run: |
          meson setup build
          meson compile -C build
      - name: Define variables ðŸ“
        id: set-pr-sha
        shell: bash
        run: echo "VERSION=$(git describe --tags | sed 's/^v//;s/_/./;s/\([^-]*-g\)/r\1/;s/-/./g')" >> "$GITHUB_OUTPUT"
      - name: Upload artifacts ðŸš€
        uses: actions/upload-artifact@v4
        with: {
          name: "tosu-overlay-${{ steps.set-pr-sha.outputs.VERSION || github.ref_name }}",
          path: build/tosu-overlay
        }