name: Build

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/build.yml"
      - "include/**/*"
      - "res/**/*"
      - "src/**/*"
      - "test/**/*"
      - "meson.build"
      - "meson.options"
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/build.yml"
      - "include/**/*"
      - "res/**/*"
      - "src/**/*"
      - "test/**/*"
      - "meson.build"
      - "meson.options"



concurrency:
  group: build-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: true
    name: Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/k4zoku/tosu-overlay-build-ci:latest
    steps:
      - name: Checkout ðŸ›’
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Build ðŸ—ï¸
        run: |
          meson setup build
          meson compile -C build
      - name: Define variables ðŸ“
        id: variables
        shell: bash
        run: |
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"
          echo "VERSION=$(git describe --tags | sed 's/^v//;s/_/./;s/\([^-]*-g\)/r\1/;s/-/./g')" >> "$GITHUB_OUTPUT"
      - name: Upload artifacts ðŸš€
        uses: actions/upload-artifact@v4
        with: {
          name: "tosu-overlay-${{ steps.variables.outputs.VERSION || github.ref_name }}",
          path: build/tosu-overlay
        }